"""add user chart_style preference

Revision ID: 7868a8c01cfe
Revises: 323b51a699aa
Create Date: 2026-09-08 22:54:02.243203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7868a8c01cfe'
down_revision = '323b51a699aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (Postgres rejects a NOT NULL add
    # without one); dropped after so the Python-side model default is what
    # governs new rows going forward, matching the other columns in this table.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_style', sa.String(length=20), nullable=False, server_default='auto'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('chart_style', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('chart_style')

    # ### end Alembic commands ###
